# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 220)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 461, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.videoRadio = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.videoRadio.setChecked(True)
        self.videoRadio.setObjectName("videoRadio")
        self.horizontalLayout.addWidget(self.videoRadio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.audioRadio = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.audioRadio.setObjectName("audioRadio")
        self.horizontalLayout.addWidget(self.audioRadio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.downloadButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_3.addWidget(self.downloadButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.quitButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout_3.addWidget(self.quitButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 2, 1, 1)
        self.pasteButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pasteButton.setObjectName("pasteButton")
        self.gridLayout.addWidget(self.pasteButton, 0, 2, 1, 1)
        self.urlEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.urlEdit.setObjectName("urlEdit")
        self.gridLayout.addWidget(self.urlEdit, 0, 1, 1, 1)
        self.typeLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.gridLayout.addWidget(self.typeLabel, 2, 0, 1, 1)
        self.urlLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.urlLabel.setObjectName("urlLabel")
        self.gridLayout.addWidget(self.urlLabel, 0, 0, 1, 1)
        self.destLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.destLabel.setObjectName("destLabel")
        self.gridLayout.addWidget(self.destLabel, 1, 0, 1, 1)
        self.destEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.destEdit.setObjectName("destEdit")
        self.gridLayout.addWidget(self.destEdit, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "YouTube Downloader"))
        self.videoRadio.setText(_translate("Form", "Video"))
        self.audioRadio.setText(_translate("Form", "Audio"))
        self.downloadButton.setText(_translate("Form", "Download"))
        self.quitButton.setText(_translate("Form", "Quit"))
        self.browseButton.setText(_translate("Form", "Browse"))
        self.pasteButton.setText(_translate("Form", "Paste"))
        self.typeLabel.setText(_translate("Form", "Type"))
        self.urlLabel.setText(_translate("Form", "URL"))
        self.destLabel.setText(_translate("Form", "Destination"))
